# Generated by Django 5.1.2 on 2024-11-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num1", models.FloatField()),
                ("num2", models.FloatField()),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("add", "Addition"),
                            ("subtract", "Subtraction"),
                            ("multiply", "Multiplication"),
                            ("divide", "Division"),
                        ],
                        max_length=10,
                    ),
                ),
                ("result", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
